### PR TITLE
Darpan_BS20B013

### PR DESCRIPTION
**Pull request by Darpan-Balar**

### CODE REVIEW

**Comment by aryanpandey** [comment]
Hey could you reorganise your repo

Add a folder called Darpan_BS20B013 and add your files in it

You don't need to close this pull request, just update your fork, the changes will get reflected here automatically

**Comment by Darpan-Balar** [comment]
where exactly should i add a folder?

**Comment by aryanpandey** [comment]
Now could you just remove the question1.py and question 2.py files from the main repo?
After that your pull is good to be merged

**Comment by Darpan-Balar** [comment]
yeah sure.. I have deleted that...now whats next?

**Comment by aryanpandey** [comment]
Nothing, it's merged now
Good work :)

**Pull request merged**
